import { Button, HTag, Paragraph } from '@/components';
import Head from 'next/head';
import { JSX } from 'react';

export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <HTag tag="h1">Hello</HTag>
        <Button appearance="primary" arrow="right">
          Узнать подробнее
        </Button>
        <Button appearance="ghost" arrow="right">
          Читать отзывы
        </Button>
        <Paragraph>
          Студенты освоят не только hard skills, необходимые для работы веб-дизайнером, но и soft skills — навыки,
          которые позволят эффективно взаимодействовать в команде с менеджерами, разработчиками и маркетологами.
          Выпускники факультета могут успешно конкурировать с веб-дизайнерами уровня middle.
        </Paragraph>
      </div>
    </>
  );
}

